// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMI4oZlMsRNKZ5K8EIjJOTujSzWERpsho',
    appId: '1:714884466695:android:a707751a55595d29e082a2',
    messagingSenderId: '714884466695',
    projectId: 'hediatyproject',
    storageBucket: 'hediatyproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsYXisMTExuqoJGM3Gbjc1ICOSVZyr99g',
    appId: '1:714884466695:ios:00390d238fc709ace082a2',
    messagingSenderId: '714884466695',
    projectId: 'hediatyproject',
    storageBucket: 'hediatyproject.firebasestorage.app',
    iosBundleId: 'com.example.hediatyProjectV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsYXisMTExuqoJGM3Gbjc1ICOSVZyr99g',
    appId: '1:714884466695:ios:00390d238fc709ace082a2',
    messagingSenderId: '714884466695',
    projectId: 'hediatyproject',
    storageBucket: 'hediatyproject.firebasestorage.app',
    iosBundleId: 'com.example.hediatyProjectV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAULNhq8nnvIe3XdFRTm0S1tG5l0gnYWa8',
    appId: '1:714884466695:web:0b4101c91893a0dbe082a2',
    messagingSenderId: '714884466695',
    projectId: 'hediatyproject',
    authDomain: 'hediatyproject.firebaseapp.com',
    storageBucket: 'hediatyproject.firebasestorage.app',
  );
}
